name: test

on: push

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Environment
      uses: actions/setup-node@v3
      with:
        node-version: '18.12.1'

    - name: Cache node
      id: node-cache
      uses: actions/cache@v3
      env:
        cache-name: cache-node-modules
      with:
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Install dependencies
      if: steps.node-cache.outputs.cache-hit != 'true'
      run: npm install

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Build
      run: npm build

    - name: Count build number
      id: number
      uses: einaregilsson/build-number@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Get current date
      if: github.event.pull_request.merged == true
      id: date
      run: echo TODAY=$(date +%Y.%m) >> $GITHUB_ENV
      
    - name: Tagging
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.TODAY }}.${{ needs.build.outputs.build_number }}
	release_name: ${{ env.TODAY }}.${{ needs.build.outputs.build_number }}
