name: production version

on:
  push:
    branches: [ production ]

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Get current data
      id: date
      run: echo YEAR=$(date +%Y) >> $GITHUB_ENV

    - name: Generate build number
      id: buildnumber
      uses: einaregilsson/build-number@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Generate tag
      uses: mathieudutour/github-tag-action@v5.5
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Generate GitHub release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: 'test'
        release_name: 'test'