name: front-end production

on:
  # pull_request:
  #   branches: [ production ]
  #   types: [ closed ]
  push:
    branches: [main]

jobs:
  tagging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get current data
        if: github.event.pull_request.merged == true
        id: date
        run: echo YEAR=$(date +%Y) >> $GITHUB_OUTPUT

      - name: Generate build number
        id: buildnumber
        uses: einaregilsson/build-number@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate tag
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate GitHub release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.date.outputs.YEAR }}.02.${{ steps.buildnumber.outputs.build_number }}
          release_name: ${{ steps.date.outputs.YEAR }}.02.${{ steps.buildnumber.outputs.build_number }}
